SET CPFROM=%FROMDIR%\Wiki\%PAGE%
SET CPTO=%TODIR%\Wiki\%TOPATH%
SET CPTODIR=%TODIR%\Wiki\%PAGE%
ECHO %CPFROM%
ECHO %CPTO%
ECHO %CPTODIR%
if not exist "%CPTODIR%" mkdir "%CPTODIR%"
copy %CPFROM%.pwd %CPTO%
