//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PersonalWiki.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PERSONTYPE                  129
#define IDD_DLGINFO                     131
#define IDD_DLGINPTODO                  132
#define IDR_EDIT_MENU                   133
#define IDD_DLGINPDATE                  134
#define IDR_DLGINFOMENU                 135
#define IDD_DlgFixedData                136
#define IDD_FIXDATAPAGE1                137
#define IDD_FIXDATAPAGE2                138
#define IDD_FIXDATAPAGE3                139
#define IDD_FIXDATAPAGE4                140
#define IDD_DLG_APP_SET                 141
#define IDD_DLG_APP_SETPAGE1            142
#define IDD_DLG_APP_SETPAGE2            143
#define IDB_SETICON                     144
#define IDD_DLG_APP_SETPAGE3            145
#define IDD_DLG_APP_SETPAGE4            146
#define IDB_WIKITREE                    147
#define IDD_DLG_APP_SETPAGE5            148
#define IDD_DLG_APP_SETPAGE6            149
#define IDD_DLG_WIKIINP                 150
#define IDD_DLG_PW_INP                  151
#define IDB_TODOSTATE                   152
#define IDD_DLG_INPWIKIPAGE             153
#define IDR_WIKIMENU                    154
#define IDD_DLG_APP_SETPAGE7            155
#define IDR_WIKIWND                     156
#define IDD_DLG_APP_SETPAGE8            156
#define IDB_WIKITOOLBAR256              161
#define IDB_MAIN_TB_IMG                 162
#define IDR_DLGWIKIINP                  163
#define IDB_DLGWIKIINP256               165
#define IDD_DLG_TODAY                   166
#define IDD_DLGURLIMP                   167
#define IDD_DLG_WIKI_PROP               168
#define IDD_DLG_PLUGIN_EXPORT           169
#define IDD_DLG_APP_SETPAGE9            170
#define IDC_BUTTON1                     1002
#define IDC_BTN_MENU                    1002
#define IDC_BTN_DEL                     1002
#define IDC_BTN_PREVIEW                 1002
#define IDC_BTN_PLG_SET                 1002
#define IDC_BTN_CONF                    1002
#define IDC_ED_NAME                     1003
#define IDC_BTN_MOD                     1003
#define IDC_LB_NAME                     1004
#define IDC_BTN_ADD                     1004
#define IDC_LB_DETAIL                   1005
#define IDC_ED_DETAIL                   1006
#define IDC_DT_PLAN_START               1007
#define IDC_LB_PLAN_START               1008
#define IDC_DT_PLAN_END                 1009
#define IDC_LB_PLAN_END                 1010
#define IDC_LB_PROCESS                  1011
#define IDC_ED_PROCESS                  1012
#define IDC_CATEGORY                    1013
#define IDC_CMB_CATEGORY                1014
#define IDC_DT_PROGRES_START            1015
#define IDC_LB_PROCESS_START            1016
#define IDC_DT_PROGRES_END              1017
#define IDC_LB_PROCESS_END              1018
#define IDC_ED_HELP                     1022
#define IDC_LIST                        1024
#define IDC_ED_MONTH                    1025
#define IDC_ED_DAY                      1026
#define IDC_ED_DATA                     1027
#define IDC_CHK_SUN                     1029
#define IDC_CHK_HOLYDAY                 1030
#define IDC_CHK_MON                     1030
#define IDC_CHK_TUE                     1031
#define IDC_CMB_OPTION                  1031
#define IDC_CHK_WED                     1032
#define IDC_CMB_DAYS                    1032
#define IDC_VIEWAREA                    1033
#define IDC_CHK_THU                     1033
#define IDC_CHK_FRI                     1034
#define IDC_RAD_2HOLIDAY                1035
#define IDC_CHK_SAT                     1035
#define IDC_RAD_CUSTOM1                 1036
#define IDC_FONTLIST                    1037
#define IDC_CHK_SATDAY                  1037
#define IDC_ED_SAMPLE                   1038
#define IDC_FONTNAMELIST                1039
#define IDC_FOTSIZELIST                 1040
#define IDC_ED_END_TODO_DEL_SPAN        1041
#define IDC_CHK_END_TODO_DEL            1042
#define IDC_CHK_USE_RET                 1043
#define IDC_COMB_CSS                    1044
#define IDC_CHK_USELOG                  1045
#define IDC_CHK_USE_FATAL_LOG           1046
#define IDC_CHK_USE_STATE_LOG           1047
#define IDC_CHK_USE_EXCEPT_LOG          1048
#define IDC_ED_WIKITEXT                 1050
#define IDC_CHK_PASSWORD                1051
#define IDC_ED_PASSWORD                 1052
#define IDC_CMB_SPAN                    1054
#define IDC_CATEGORYLIST                1055
#define IDC_ED_CATEGORY                 1056
#define IDC_CMB_STATE                   1057
#define IDC_CHK_SUNDAY                  1061
#define IDC_CHK_MONDAY                  1062
#define IDC_CHK_TUEDAY                  1063
#define IDC_CHK_WEDDAY                  1064
#define IDC_CHK_THUDAY                  1065
#define IDC_CHK_FRIDAY                  1066
#define IDC_RAD_NONE                    1068
#define IDC_TIME                        1069
#define IDC_PLG_LIST                    1070
#define IDC_ED_PLG_DETAIL               1071
#define IDC_ATTACHLIST                  1072
#define IDC_RAD_SC                      1073
#define IDC_RAD_MEMO                    1074
#define IDC_CHK_TBLINK                  1075
#define IDC_CHK_SHOWATTACH              1076
#define IDC_CHK_CONV_TIME               1077
#define IDC_LIST1                       1078
#define IDC_SPDAY_LIST                  1078
#define IDC_SET_LIST                    1078
#define IDC_EDIT1                       1079
#define IDC_ED_EXT                      1079
#define IDC_ED_PATH1                    1079
#define IDC_ED_TODAY                    1079
#define IDC_ED_URL                      1079
#define IDC_ED_WIKIPATH                 1079
#define IDC_EDIT2                       1080
#define IDC_ED_MIME                     1080
#define IDC_ED_PATH3                    1080
#define IDC_ED_NEXTDAY                  1080
#define IDC_ED_PAGE                     1080
#define IDC_ED_CREATEDATE               1080
#define IDC_CHK_USE                     1081
#define IDC_ED_PATH2                    1081
#define IDC_ED_NEXTNEXTDAY              1081
#define IDC_ED_UPDATEDATE               1081
#define IDC_CHK_SC                      1082
#define IDC_ED_PATH4                    1082
#define IDC_CHK_FIX                     1083
#define IDC_CHK_TODO                    1084
#define IDC_HTMLDUMMY                   1085
#define IDC_CHK_USE_USB_LINK            1086
#define IDC_CHK_NETDRV                  1087
#define IDC_CHK_USE_TODAY               1088
#define IDC_ED_ID                       1089
#define IDC_ED_PW                       1090
#define IDC_CHK_CRYPT                   1091
#define IDC_CHK_COLD                    1092
#define IDC_FONT_NAME_LIST              1093
#define IDC_FONT_SIZE_LIST              1094
#define IDC_CMB_EXPORT                  1095
#define IDC_CHK_RUN_MAINWND_SHOW        1097
#define IDC_CHK_VIEW_SEC                1099
#define IDC_SHOWTIME                    1101
#define IDM_TODO_ADD                    32771
#define IDM_TODO_EDIT                   32772
#define IDM_TODO_DEL                    32773
#define IDM_FIXED_DATA                  32774
#define IDM_PWIKI_SET                   32775
#define IDM_CLOSE                       32776
#define IDM_DUMMY                       32778
#define IDM_ADDWIKI                     32779
#define IDM_EDITWIKI                    32780
#define IDM_DELWIKI                     32781
#define IDM_EXP_HTML                    32782
#define IDM_EXP_TEXT                    32783
#define IDM_RENAME_WIKI                 32784
#define IDM_RULE                        32788
#define IDM_HELP                        32789
#define ID_BUTTON32792                  32792
#define ID_WIKI_BOLD                    32792
#define ID_WIKI_ITALIC                  32793
#define ID_WIKI_UNDERLINE               32794
#define ID_WIKI_STRIKE                  32795
#define ID_WIKI_LIST                    32796
#define ID_WIKI_NUMLIST                 32797
#define ID_WIKI_HEAD                    32798
#define ID_WIKI_LINK                    32799
#define ID_WIKI_RET                     32800
#define ID_WIKI_HLINE                   32801
#define IDM_PROPERTY                    32802
#define ID_BTN_TREEREFRESH              32803
#define IDM_URL_IMPORT                  32804
#define ID_APP_END                      32805
#define IDM_PLUGIN_EXPORT               32806
#define IDC_NEXTBTN                     59393
#define IDC_PREVBTN                     59394
#define IDC_DTCTRL                      59395
#define IDC_TAB                         59396
#define IDS_WIKITREE                    59397
#define IDC_PWIKI_BALLOON               59398
#define IDS_BTN_WIKIADD                 59399
#define IDS_BTN_WIKIEDIT                59400
#define IDS_BTN_WIKIDEL                 59401
#define IDS_BTN_FIND                    59402
#define IDS_CMB_FIND                    59403
#define IDS_FIND_LIST                   59404
#define IDS_TODOLIST1                   59405
#define IDS_TODOLIST2                   59406
#define IDS_TODOLIST3                   59407
#define IDS_TODOLIST4                   59408
#define IDS_TODOLIST5                   59409
#define IDS_TODOLIST6                   59410
#define IDS_TODOLIST7                   59411
#define IDS_PREVIEW                     59412
#define IDS_CALWND                      59413
#define IDS_WIKIWND                     59414
#define IDS_FINDWND                     59415
#define IDS_MEMOTAB                     59416
#define IDC_TODAYBTN                    59417
#define IDC_WIKITAB                     59418
#define IDC_WIKIEDITWND                 59419
#define IDC_HTMLVIEW                    59420
#define IDS_TODOLIST8                   59421
#define IDS_CH_HSCROLLBAR               59422
#define IDS_CH_VSCROLLBAR               59423
#define IDS_CMB_FILTER_STATE            59424
#define IDS_CMB_FILTER_CATEGORY         59425
#define IDC_TODOTAB                     61191
#define IDS_TODOCHKTIMER                61192

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
